name: Build on Windows

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-2025

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET SDK via Chocolatey
        shell: pwsh
        run: |
          choco install dotnet-6.0-sdk -y

      - name: Restore NuGet Packages
        run: dotnet restore Mods.sln

      - name: Build All Projects
        run: dotnet build Mods.sln -c Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: |
            BadAPI/bin/Release/net6.0-windows/win-x64
            FPSCounter/bin/Release/net6.0-windows/win-x64
            ShovelHotkey/bin/Release/net6.0/win-x64
